name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: Tag repository
      run: git tag -a v1.0.0 -m "Version 1.0.0"  # Replace with your desired version and message
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    - name: Push tag to GitHub
      run: git push origin --tags
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*  # Adjust this pattern based on your build output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
